name: Static analysis
on: [push]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "cache=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Restore Composer Cache
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.composer-cache.outputs.cache }}
          key: composer-${{ hashFiles('**/composer.json') }}
          restore-keys: composer

      - name: Install Dependencies
        uses: nick-invision/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
